server:
  port: 7001
spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-product # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://MICROSERVICE-PRODUCT
          predicates:
            - Path=/product/get/** # 断言，路径相匹配的进行路由

eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    prefer-ip-address: true #访问路径可以显示IP地址
feign:
  hystrix:
    enabled: true # 需要开启 hystrix
